# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60728fdaa6d16d815a116f824b828df86bcb30ae0752f7c93d8ec4cbf782564194999abac9940c024f6b7238e253027fe8160ccb06f66ff53883109119d1d4a8

test:
  secret_key_base: c206c23002a3fc9b19ec5086a880fe96ed3a74cbf0469005876058717b04d1620d8cad473fd368b8792cfcefad0ab2d46079098c753a812e0f295a9c47ff307a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 447ef40dea02dc1f8a44287e433d310295a5dc3ebea04e6bb6104ece0c33e38633f4b3141d6be020f981c5aad038296d88625f36be8289d47d49b3bebcd3e08b
